### ISSUE TITLE
404 Error. Cannot download the checkpoints from GoogleDrive.

### ISSUE THREAD

**Issue by xyzhang77** [pleshro/GlassesGAN_release#6]
Hi, pleshro, thanks for your work!

While downing files in the jupter notebook, it shows 404 error, just like [this](https://drive.usercontent.google.com/download?id=1y-lZHZhJ_QYyqGfH-EGmuzOigExqLfqq&export=download). 

Could you please publish the checkpoints once again?

**Comment by adib-vali** [comment]
It shows 404 error for me too. It seems checkpoints were removed :]

**Comment by pleshro** [comment]
Sorry for the inconvenience, until I find a more sustainable location for the weights, the following folder should have what you need. https://drive.google.com/open?id=1N8SNUuk3zr8CoZo1Mc1q_JnJOtbG7nDe&usp=drive_fs

**Comment by xyzhang77** [comment]
Thank you for your response! I am now able to download successfully!

**Comment by Cinnameldehyde** [comment]
The link provided doesn't seem to be working anymore and I was encountering issue due to the inavailability while running the code on collab. It looks like it was removed at some point. Do you mind sharing again?

**Comment by pleshro** [comment]
Hello, Please find the download links below.
[aveglassesdiff_celebhq_dataset_results_RG.npy]
(https://drive.google.com/file/d/1FXTPEkyaSFN_IRZq04_pF-iD0qnyPgwf/view?usp=drive_link)
[aveglassesdiff_celebhq_dataset_results_SG.npy]
(https://drive.google.com/file/d/1h7AGjY4EZDNVLJe2fLkXhrHdLUJzNRiS/view?usp=drive_link)
[deeplab_epoch_19.pth]
(https://drive.google.com/file/d/1rn2HJXLn1qC8c-6OARrWPw7IFbddt9eo/view?usp=drive_link)
[e4e_ffhq_encode.pt]
(https://drive.google.com/file/d/1lydmMcVZUV-tr6gKp8Tv-icD3uvAwCED/view?usp=drive_link)
[fitted_pca_celebhq_dataset_results.joblib]
(https://drive.google.com/file/d/1XeGJ6bMulBwtRj7PvK6NSRHN16E3yCsv/view?usp=drive_link)
